# turing_garden = Garden.create!(name: 'Turing Community Garden', organic: true)
# library_garden = Garden.create!(name: 'Public Library Garden', organic: true)
# other_garden = Garden.create!(name: 'Main Street Garden', organic: false)

# turing_garden.plots.create!(number: 25, size: "Large", direction: "East")
# turing_garden.plots.create!(number: 26, size: "Small", direction: "West")
# library_garden.plots.create!(number: 2, size: "Small", direction: "South")
# other_garden.plots.create!(number: 738, size: "Medium", direction: "West")

plant1 = Plant.create!(name: "Swiss Chard", description: "Bitter and nice", days_to_harvest: 80)
plant2 = Plant.create!(name: "Tomato", description: "One giant tomato", days_to_harvest: 120)
plant3 = Plant.create!(name: "Squash", description: "Like a cucumber but scary", days_to_harvest: 100)

garden1 = Garden.create!(name: "Stanton", organic: true)
  plot1_garden1 = Plot.create!(number: 25, size: "Large", direction: "East", garden_id: garden1.id)
    plotplant1 = PlotPlant.create!(plot_id: plot1_garden1.id, plant_id: plant1.id)
    plotplant2 = PlotPlant.create!(plot_id: plot1_garden1.id, plant_id: plant2.id)
  plot2_garden1 = Plot.create!(number: 12, size: "Small", direction: "South", garden_id: garden1.id)
    plotplant3 = PlotPlant.create!(plot_id: plot2_garden1.id, plant_id: plant3.id)
garden2 = Garden.create!(name: "Barnard", organic: false)
  plot1_garden2 = Plot.create!(number: 5, size: "Medium", direction: "North", garden_id: garden2.id)
    plotplant4 = PlotPlant.create!(plot_id: plot1_garden2.id, plant_id: plant1.id)